SIMULATION_CONFIG = {
    "lrMethods": ["DAQ","OGD","SBRD"],
    "Hybrid_funcs": ["DAQ", "DAH"],
    "T": 100,
    "alpha": 1,
    "n": 3,
    "eta": 0.5,
    "price": 1.0,
    "a": 100,
    "mu": 0,
    "c": 4000,
    "delta": 0.1,
    "epsilon": 1e-3,
    "tol": 1e-5,
    "lr_vary": False,
    "IdxConfig": 1,
    "x_label": "Time step (t)",
    "metric": "utility",
    "y_label": r"$\varphi (z)$",
    "ylog_scale": False,
    "plot_step": 10,
    "saveFileName": "results/plot_",
    "pltText": False,
    "gamma": 0.5
}